export type OpenImageModelStatus = 'installed-local' | 'external-trial' | 'gpu-required' | 'license-review';

export type OpenImageModel = {
  id: string;
  name: string;
  tasks: string[];
  sourceUrl: string;
  license: string;
  commercialUse: string;
  size: string;
  minimumRam: string;
  minimumVram: string;
  localUse: string;
  status: OpenImageModelStatus;
  notes: string;
  comfyUi: boolean;
};

export const OPEN_IMAGE_MODELS: OpenImageModel[] = [
  { id: 'u2netp', name: 'U2NetP', tasks: ['إزالة الخلفية'], sourceUrl: 'https://github.com/danielgatis/rembg', license: 'Apache-2.0', commercialUse: 'نعم — مصدر تمت مراجعته', size: 'نحو 4.6 MiB في التطبيق', minimumRam: 'هاتف حديث أو متصفح حديث', minimumVram: 'لا يحتاج GPU', localUse: 'مدعوم داخل التطبيق الآن', status: 'installed-local', notes: 'المسار المحلي الموجود لإزالة خلفية قطعة الملابس؛ لا يُنزّل هنا من جديد.', comfyUi: false },
  { id: 'kolors-vton', name: 'Kolors Virtual Try-On', tasks: ['Virtual Try-On'], sourceUrl: 'https://huggingface.co/spaces/Kwai-Kolors/Kolors-Virtual-Try-On', license: 'Demo في Hugging Face', commercialUse: 'راجع شروط الـSpace', size: 'غير منشور للتنزيل هنا', minimumRam: 'متصفح واتصال شبكة', minimumVram: 'لا ينطبق على الهاتف', localUse: 'تجربة خارجية يدوية فقط', status: 'external-trial', notes: 'يحتاج صورة شخص وقطعة ملابس. لا ينشر الـSpace API مسمى ثابتاً، لذلك لا يعمل تلقائياً داخل التطبيق.', comfyUi: false },
  { id: 'catvton', name: 'CatVTON', tasks: ['Virtual Try-On'], sourceUrl: 'https://huggingface.co/zhengchong/CatVTON', license: 'CC BY-NC-SA 4.0', commercialUse: 'لا — غير تجاري', size: '899.06M معلمات', minimumRam: 'بيئة Python منفصلة', minimumVram: 'أقل من 8 GiB عند 1024×768 وفق المصدر', localUse: 'يتطلب GPU منفصلاً', status: 'license-review', notes: 'له Workflow رسمي لـComfyUI، لكنه لا يعمل على هاتف المستخدم أو استضافة المشروع الحالية.', comfyUi: true },
  { id: 'idm-vton', name: 'IDM-VTON', tasks: ['Virtual Try-On'], sourceUrl: 'https://huggingface.co/yisol/IDM-VTON', license: 'CC BY-NC-SA 4.0', commercialUse: 'لا — غير تجاري', size: 'غير مثبت في الكتالوج', minimumRam: 'بيئة Python وGPU', minimumVram: 'GPU مطلوب؛ راجع المصدر', localUse: 'يتطلب GPU منفصلاً', status: 'license-review', notes: 'تجربة عامة متاحة، لكن النموذج لا ينشره Hugging Face عبر Inference Provider رسمي حالياً.', comfyUi: false },
  { id: 'ootdiffusion', name: 'OOTDiffusion', tasks: ['Virtual Try-On'], sourceUrl: 'https://github.com/levihsu/OOTDiffusion', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'مراجعة مطلوبة', minimumRam: 'بيئة Python منفصلة', minimumVram: 'GPU مطلوب', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'يظهر في البحث كخيار للملابس الكاملة، لكن لا يفعّل قبل مراجعة رخصته ومتطلبات أوزانه.', comfyUi: false },
  { id: 'flux-schnell', name: 'FLUX.1 Schnell', tasks: ['Text to Image'], sourceUrl: 'https://huggingface.co/black-forest-labs/FLUX.1-schnell', license: 'Apache-2.0', commercialUse: 'نعم — مصدر تمت مراجعته', size: '12B BF16', minimumRam: 'بيئة Python وملفات كبيرة', minimumVram: 'GPU مطلوب؛ راجع المصدر', localUse: 'يتطلب جهازاً منفصلاً', status: 'gpu-required', notes: 'نموذج نص إلى صورة؛ لا يلبس قطعة ملابس مرفوعة وحده.', comfyUi: true },
  { id: 'flux-dev', name: 'FLUX.1 Dev', tasks: ['Text to Image'], sourceUrl: 'https://huggingface.co/black-forest-labs/FLUX.1-dev', license: 'FLUX.1-dev Non-Commercial', commercialUse: 'لا — غير تجاري', size: '12B BF16', minimumRam: 'بيئة Python وملفات كبيرة', minimumVram: 'GPU مطلوب؛ راجع المصدر', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'جودة أعلى محتملة، لكن رخصته غير تجارية ولا يناسب هاتف المستخدم.', comfyUi: true },
  { id: 'sd15', name: 'Stable Diffusion 1.5', tasks: ['Text to Image', 'Image to Image', 'Inpainting'], sourceUrl: 'https://huggingface.co/stable-diffusion-v1-5/stable-diffusion-v1-5', license: 'CreativeML Open RAIL-M', commercialUse: 'راجع شروط الإصدار والـcheckpoint', size: 'تختلف حسب الـcheckpoint', minimumRam: 'بيئة Python منفصلة', minimumVram: 'GPU موصى به', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'عائلة مرنة لكن الرخصة ووزن كل checkpoint يراجعان قبل الاستخدام.', comfyUi: true },
  { id: 'sdxl', name: 'Stable Diffusion XL', tasks: ['Text to Image', 'Image to Image', 'Inpainting'], sourceUrl: 'https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0', license: 'OpenRAIL++', commercialUse: 'راجع شروط الإصدار', size: 'أكبر من SD 1.5', minimumRam: 'بيئة Python منفصلة', minimumVram: 'GPU أكبر من SD 1.5', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'مناسب للتجارب البصرية عند توفر GPU، وليس مساراً محلياً للهاتف.', comfyUi: true },
  { id: 'kandinsky', name: 'Kandinsky', tasks: ['Text to Image', 'Image to Image'], sourceUrl: 'https://huggingface.co/kandinsky-community/kandinsky-3', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'مراجعة مطلوبة', minimumRam: 'بيئة Python منفصلة', minimumVram: 'GPU مطلوب', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'بديل بحثي لتوليد الصور؛ لا يفعّل تلقائياً.', comfyUi: false },
  { id: 'pixart', name: 'PixArt', tasks: ['Text to Image'], sourceUrl: 'https://huggingface.co/PixArt-alpha/PixArt-XL-2-1024-MS', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'مراجعة مطلوبة', minimumRam: 'بيئة Python منفصلة', minimumVram: 'GPU مطلوب', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'عائلة توليد صور للتجارب والمقارنة، لا تنفذ على الهاتف.', comfyUi: false },
  { id: 'hunyuan-dit', name: 'Hunyuan-DiT', tasks: ['Text to Image'], sourceUrl: 'https://huggingface.co/Tencent-Hunyuan/HunyuanDiT-Diffusers', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'مراجعة مطلوبة', minimumRam: 'بيئة Python منفصلة', minimumVram: 'GPU مطلوب', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'نموذج بحثي ثقيل؛ يسجل للمعرفة فقط حتى تراجع الرخصة والعتاد.', comfyUi: false },
  { id: 'playground-v25', name: 'Playground v2.5', tasks: ['Text to Image'], sourceUrl: 'https://huggingface.co/playgroundai/playground-v2.5-1024px-aesthetic', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'مراجعة مطلوبة', minimumRam: 'بيئة Python منفصلة', minimumVram: 'GPU مطلوب', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'يعرض للمقارنة البصرية فقط؛ لا يوصف كتشغيل مجاني داخل التطبيق.', comfyUi: false },
  { id: 'openjourney', name: 'OpenJourney', tasks: ['Style Transfer', 'Text to Image'], sourceUrl: 'https://huggingface.co/prompthero/openjourney-v4', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'مراجعة مطلوبة', minimumRam: 'بيئة Python منفصلة', minimumVram: 'GPU مطلوب', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'خاص بالأساليب الفنية ولا يعرض كبديل رسمي لأي علامة أو منتج.', comfyUi: true },
  { id: 'real-esrgan', name: 'Real-ESRGAN', tasks: ['Upscaling', 'Image Enhancement'], sourceUrl: 'https://github.com/xinntao/Real-ESRGAN', license: 'BSD-3-Clause', commercialUse: 'نعم — مصدر تمت مراجعته', size: 'يتغير حسب الوزن', minimumRam: 'بيئة منفصلة', minimumVram: 'GPU موصى به للجودة والسرعة', localUse: 'يتطلب جهازاً منفصلاً', status: 'gpu-required', notes: 'يرفع الدقة؛ لا يخلق تفاصيل مضمونة لم تكن موجودة في الصورة.', comfyUi: true },
  { id: 'gfpgan', name: 'GFPGAN / CodeFormer', tasks: ['Face/Detail Enhancement'], sourceUrl: 'https://github.com/TencentARC/GFPGAN', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'يتغير حسب الوزن', minimumRam: 'بيئة منفصلة', minimumVram: 'GPU موصى به', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'يستخدم فقط لتحسين صور مأذون بها، وليس لتبديل الهوية أو انتحالها.', comfyUi: true },
  { id: 'rmbg', name: 'RMBG / BRIA', tasks: ['Background Removal'], sourceUrl: 'https://huggingface.co/briaai/RMBG-1.4', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'يتغير حسب الوزن', minimumRam: 'بيئة منفصلة', minimumVram: 'GPU موصى به', localUse: 'بديل بحثي فقط', status: 'license-review', notes: 'لا يحل محل U2NetP المحلي إلا بعد ترخيص واختبار مستقلين.', comfyUi: false },
  { id: 'blip', name: 'BLIP / BLIP-2', tasks: ['Image Captioning', 'Image Analysis'], sourceUrl: 'https://github.com/salesforce/BLIP', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'يتغير حسب الإصدار', minimumRam: 'بيئة منفصلة', minimumVram: 'GPU موصى به', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'يمكنه اقتراح وصف للصورة، لا يستخدم كوصف حقيقة مؤكدة للإنسان أو هويته.', comfyUi: false },
  { id: 'clip', name: 'CLIP', tasks: ['Image Analysis', 'Image/Text Similarity'], sourceUrl: 'https://github.com/openai/CLIP', license: 'MIT', commercialUse: 'نعم — مصدر تمت مراجعته', size: 'يتغير حسب الإصدار', minimumRam: 'بيئة منفصلة', minimumVram: 'GPU موصى به للسرعة', localUse: 'يتطلب جهازاً منفصلاً', status: 'gpu-required', notes: 'للتشابه والترتيب وليس لتشخيص الأشخاص أو اتخاذ قرارات عنهم.', comfyUi: false },
  { id: 'sam', name: 'Segment Anything (SAM)', tasks: ['Segmentation', 'Masks for Inpainting'], sourceUrl: 'https://github.com/facebookresearch/segment-anything', license: 'Apache-2.0', commercialUse: 'نعم — مصدر تمت مراجعته', size: 'يتغير حسب الوزن', minimumRam: 'بيئة منفصلة', minimumVram: 'GPU موصى به', localUse: 'يتطلب جهازاً منفصلاً', status: 'gpu-required', notes: 'يفصل العناصر ويجهز أقنعة، ولا يستبدل موافقة صاحب الصورة.', comfyUi: false },
  { id: 'controlnet', name: 'ControlNet', tasks: ['ControlNet', 'Pose', 'Depth', 'Lineart'], sourceUrl: 'https://github.com/lllyasviel/ControlNet', license: 'Apache-2.0', commercialUse: 'نعم — مصدر تمت مراجعته', size: 'يعتمد على النموذج الأساسي', minimumRam: 'بيئة منفصلة', minimumVram: 'GPU للنموذج الأساسي', localUse: 'يتطلب جهازاً منفصلاً', status: 'gpu-required', notes: 'طبقة تحكم فوق SD/SDXL وليست نموذج توليد مستقل.', comfyUi: true },
  { id: 'ip-adapter', name: 'IP-Adapter', tasks: ['Image Reference', 'Style Transfer'], sourceUrl: 'https://github.com/tencent-ailab/IP-Adapter', license: 'Apache-2.0', commercialUse: 'نعم — مصدر تمت مراجعته', size: 'يعتمد على النموذج الأساسي', minimumRam: 'بيئة منفصلة', minimumVram: 'GPU للنموذج الأساسي', localUse: 'يتطلب جهازاً منفصلاً', status: 'gpu-required', notes: 'يستخدم صورة مرجعية للتحكم في الأسلوب أو الشكل، مع احترام موافقة صاحب الصورة.', comfyUi: true },
  { id: 'instantid', name: 'InstantID', tasks: ['Face/Detail Enhancement', 'Image Reference'], sourceUrl: 'https://github.com/instantX-research/InstantID', license: 'مراجعة مطلوبة', commercialUse: 'راجع المصدر', size: 'مراجعة مطلوبة', minimumRam: 'بيئة منفصلة', minimumVram: 'GPU مطلوب', localUse: 'يتطلب جهازاً منفصلاً', status: 'license-review', notes: 'لا يستخدم لصور الأشخاص إلا بإذن واضح؛ لا يفعّل داخل المشروع.', comfyUi: true },
];

export const OPEN_IMAGE_MODEL_STATUS: Record<OpenImageModelStatus, string> = {
  'installed-local': 'مثبت محلياً',
  'external-trial': 'تجربة خارجية',
  'gpu-required': 'يتطلب GPU',
  'license-review': 'مراجعة الترخيص',
};
