import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {fileURLToPath} from 'node:url';import {createSignedToken} from './token-lib.mjs';
const envFile=new URL('../.env',import.meta.url);
if(!process.env.NODE_ENV){try{const text=fs.readFileSync(envFile,'utf8');for(const line of text.split(/\r?\n/)){const m=line.match(/^\s*([A-Z_][A-Z0-9_]*)\s*=\s*(.*?)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['\"]|['\"]$/g,'')}}catch{}}
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),publicDir=path.join(root,'public'),tokensFile=path.join(root,'server','tokens.json'),keysDir=path.join(root,'server','keys');
const port=Number(process.env.PORT||4173),env=process.env.NODE_ENV||'development',developerSecret=process.env.DEVELOPER_SECRET||'';
if(env==='production'&&developerSecret.length<32){console.error('FATAL: DEVELOPER_SECRET must be set to 32+ chars in production');process.exit(1)}
const secret=developerSecret||'development-secret-only-not-for-production-32chars';
fs.mkdirSync(keysDir,{recursive:true});
const keyFile=path.join(keysDir,'activation.json');
let keypair;
if(fs.existsSync(keyFile)){keypair=JSON.parse(fs.readFileSync(keyFile,'utf8'));}else{const k=crypto.generateKeyPairSync('ed25519');keypair={publicKey:k.publicKey.export({type:'spki',format:'pem'}),privateKey:k.privateKey.export({type:'pkcs8',format:'pem'})};fs.writeFileSync(keyFile,JSON.stringify(keypair,null,2));}
function readTokens(){try{return JSON.parse(fs.readFileSync(tokensFile,'utf8'))}catch{return []}}function writeTokens(v){fs.writeFileSync(tokensFile,JSON.stringify(v,null,2))}function json(res,s,d){const b=JSON.stringify(d);res.writeHead(s,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(b)}function body(req){return new Promise((ok,no)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1e6)no(new Error('too-large'))});req.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch{no(new Error('bad-json'))}})})}function code(){return 'CLOTH-'+crypto.randomBytes(8).toString('hex').toUpperCase()}
function serve(req,res){let u=decodeURIComponent(new URL(req.url,'http://x').pathname);if(u==='/')u='/index.html';const f=path.normalize(path.join(publicDir,u));if(!f.startsWith(publicDir))return res.writeHead(403).end();fs.readFile(f,(e,d)=>{if(e)return res.writeHead(404).end('Not found');const t={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.json':'application/json','.webmanifest':'application/manifest+json'}[path.extname(f)]||'application/octet-stream';res.writeHead(200,{'Content-Type':t,'Cache-Control':u==='/sw.js'?'no-cache':'public, max-age=3600'});res.end(d)})}
http.createServer(async(req,res)=>{if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Headers':'Content-Type,X-Developer-Secret','Access-Control-Allow-Methods':'GET,POST,OPTIONS'});return res.end()}
if(req.method==='GET'&&req.url==='/api/activation/public-key')return json(res,200,{publicKey:keypair.publicKey});
if(req.method==='GET'&&req.url==='/api/health')return json(res,200,{ok:true,version:'2.0.0'});
if(req.method==='POST'&&req.url==='/api/developer/tokens'){if(req.headers['x-developer-secret']!==secret)return json(res,401,{error:'غير مصرح'});try{const b=await body(req),r={code:code(),createdAt:Date.now(),expiresAt:Date.now()+Math.min(Math.max(Number(b.days)||30,1),3650)*86400000};const all=readTokens();all.push(r);writeTokens(all);return json(res,200,r)}catch{return json(res,400,{error:'طلب غير صالح'})}}
if(req.method==='POST'&&req.url==='/api/activate'){try{const b=await body(req),r=readTokens().find(x=>x.code===String(b.code||'').trim());if(!r)return json(res,404,{error:'الرمز غير موجود'});if(Date.now()>=r.expiresAt)return json(res,410,{error:'الرمز منتهي'});const token=createSignedToken({id:crypto.randomUUID(),issuedAt:Date.now(),expiresAt:r.expiresAt,privateKey:crypto.createPrivateKey(keypair.privateKey)});return json(res,200,{active:true,token,expiresAt:r.expiresAt,publicKey:keypair.publicKey})}catch{return json(res,400,{error:'طلب غير صالح'})}}
serve(req,res)}).listen(port,()=>console.log(`Clothing Ad Generator v2: http://localhost:${port}`));
